Aligning to new AdapterIdFragment
BHoM/GSA_Toolkit pull request #205
Opened 2020-10-20 10:20 UTC by alelom

### NOTE: Depends on 

BHoM/BHoM#1033

 ### Issues addressed by this PR

 Closes #204 

 

 ### Test files

 ### Changelog

 ### Additional comments

2020-10-27 14:51 UTC, IsakNaslundBh reviewed
See some initial comments below. Was hoping we could get away with not having the get and set GSAId methods, but given how much it is used in the engine it might be tricky, which might render some of my suggestions a bit useless, but have a look and then we can chat!

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +            return ComCall(Convert.IToGsaString(obj, obj.GSAId().ToString()));
```suggestion
            return ComCall(Convert.IToGsaString(obj, GetAdapterId<int>(obj).ToString()));
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +            return ComCall(Convert.IToGsaString(prop, prop.GSAId().ToString()));
```suggestion
            return ComCall(Convert.IToGsaString(prop,  GetAdapterId<int>(prop).ToString()));
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +                success &= ComCall(Convert.ToGsaString(link, link.GSAId().ToString(), 0));
```suggestion
                success &= ComCall(Convert.ToGsaString(link, GetAdapterId<int>(link).ToString(), 0));
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +                    allIds.Add(link.AdapterId<int>(typeof(GSAId)));
Order switch here of these two lines I think is critical
```suggestion
                    allIds.Add(GetAdapterId<int>(link));
                    link.Fragments.Remove(typeof(GSAId)); // to remove the existing single id on the link
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +            mesh.SetGSAId(allIds);
```suggestion
            SetAdapterId(mesh, allIds);
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, ISectionProperty> secProps = secPropList.Where(x => x != null).ToDictionary(x => x.GSAId().ToString());
```suggestion
            Dictionary<string, ISectionProperty> secProps = secPropList.Where(x => x != null).ToDictionary(x => GetAdapterId<int>(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, Node> nodes = nodeList.ToDictionary(x => x.GSAId().ToString());
```suggestion
            Dictionary<string, Node> nodes = nodeList.ToDictionary(x => GetAdapterId<int>(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, IMaterialFragment> materials = matList.ToDictionary(x => (x.GSAId().ToString() ?? x.Name).ToString());
With the Id now being obejct, can store default names with string in the Id
```suggestion
            Dictionary<string, IMaterialFragment> materials = matList.ToDictionary(x => GetAdapterId(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, IMaterialFragment> materials = matList.ToDictionary(x => x.GSAId().ToString() ?? x.Name);
```suggestion
            Dictionary<string, IMaterialFragment> materials = matList.ToDictionary(x => GetAdapterId(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, ISurfaceProperty> props = secPropList.ToDictionary(x => x.GSAId().ToString());
```suggestion
            Dictionary<string, ISurfaceProperty> props = secPropList.ToDictionary(x => GetAdapterId<int>(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, Node> nodes = nodeList.ToDictionary(x => x.GSAId().ToString());
```suggestion
            Dictionary<string, Node> nodes = nodeList.ToDictionary(x => GetAdapterId<int>(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, LinkConstraint> constraints = constraintList.ToDictionary(x => x.GSAId().ToString());
```suggestion
            Dictionary<string, LinkConstraint> constraints = constraintList.ToDictionary(x => GetAdapterId<int>(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            Dictionary<string, Node> nodes = nodeList.ToDictionary(x => x.GSAId().ToString());
```suggestion
            Dictionary<string, Node> nodes = nodeList.ToDictionary(x => GetAdapterId<int>(x).ToString());
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Read.cs
> +            materials.Add(new Aluminium() { Name = "ALUMINIUM" });
Goes together with the change for reading sections and surface properties
```suggestion
            materials.Add(new Steel() { Name = "STEEL" });
            materials.Add(new Concrete() { Name = "CONC_SHORT" });
            materials.Add(new Concrete() { Name = "CONC_LONG" });
            materials.Add(new Aluminium() { Name = "ALUMINIUM" });

            foreach (IMaterialFragment material in materials)
            {
                SetAdapterId(material, material.Name);
            }
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/ReadResultsElements.cs
>                          idsOut.Add(id);
```suggestion
                    else if (o is IBHoMObject )
                    {
                        id = GetAdapterId<int>((IBHoMObject)o);
                        if (id != 0)
                            idsOut.Add(id);
                    }
```

2020-10-27 14:51 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Update.cs
> +                success &= ComCall(Convert.ToGsaString(mesh, (int)mesh.GSAId(), 0));
```suggestion
                success &= ComCall(Convert.ToGsaString(mesh, GetAdapterId<int>(mesh), 0));
```

2020-10-28 10:10 UTC, IsakNaslundBh requested changes
Small tweak to the rigid links ids

2020-10-28 10:10 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +                    allIds.Add(GetAdapterId<int>(link));
This we should change to this to make the Ids line up with the secondary nodes

```suggestion
                    allIds.Insert(0, GetAdapterId<int>(link));
```

2020-10-28 16:15 UTC, IsakNaslundBh requested changes
All working fine, just final clean-up of no longer used method and some comment lines

2020-10-28 16:15 UTC, IsakNaslundBh commented on GSA_Engine/Query/GSAId.cs
> +        }
Think this can be removed. Not used anywhere in the code

```suggestion

```

2020-10-28 16:15 UTC, IsakNaslundBh commented on GSA_Engine/Modify/SetGSAId.cs
> +        }
```suggestion
        /***************************************************/
        /**** Public Methods                            ****/
        /***************************************************/
        
        public static void SetGSAId(this IBHoMObject BHoMObject, object id)
        {
            BHoMObject.SetAdapterId(typeof(GSAId), id);
        }
        
        /***************************************************/
```

2020-10-29 08:53 UTC, IsakNaslundBh requested changes
Tweak for mesh update

2020-10-29 08:53 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Update.cs
> +                if (mesh == null || GetAdapterId(mesh) != null || mesh.Faces.Count != 1)
```suggestion
                if (mesh == null || GetAdapterId(mesh) == null || mesh.Faces.Count != 1)
```

2020-10-29 08:55 UTC, alelom commented on GSA_Adapter/CRUD/Update.cs
> +                if (mesh == null || GetAdapterId(mesh) != null || mesh.Faces.Count != 1)
Good catch

2020-10-29 09:32 UTC, IsakNaslundBh approved these changes
LGTM now!

2020-10-29 10:59 UTC, IsakNaslundBh commented
/azp run GSA_Toolkit.CheckInstaller

2020-10-29 14:39 UTC, merged