Add support for pushing fabric structures
BHoM/GSA_Toolkit pull request #233
Opened 2021-02-20 13:57 UTC by johannaisak

Adds fabric material, fabric panel property, spacers, spacer properties, soap stress plus enables pushing of these

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #232 

 

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/GSA_Toolkit/%23232%20-%20AddSupportForPushingFabricStructures/fabric%20push.gh?csf=1&web=1&e=rBhXn8

 ### Changelog

 ### Additional comments

Adds fabric material, fabric panel property, spacers, spacer properties, soap stress + enables push of these

2021-05-17 09:29 UTC, annastigenberg approved these changes
Looks good to me!

2021-06-01 10:23 UTC, IsakNaslundBh commented
@BHoMBot check project-compliance

2021-06-01 11:30 UTC, IsakNaslundBh commented
@BHoMBot check project-compliance

2021-06-01 11:57 UTC, IsakNaslundBh commented
@BHoMBot fix project file ref. 2718115227

2021-06-01 12:04 UTC, IsakNaslundBh requested changes
Small tweak below. Should be using the constructed face, rather than pick a new one

2021-06-01 12:04 UTC, IsakNaslundBh commented on GSA_Adapter/Convert/FromGsa/Elements/FEMesh.cs
> +                    Faces = new List<FEMeshFace>() { new FEMeshFace() { NodeListIndices = Enumerable.Range(0, gsaMesh.NumTopo).ToList() } },
```suggestion
                    Faces = new List<FEMeshFace>() { face },
```

2021-06-02 14:19 UTC, IsakNaslundBh commented
@BHoMBot check installer

2021-06-02 14:19 UTC, IsakNaslundBh approved these changes
Works fine. Nice work!

2021-06-02 14:41 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-06-02 15:16 UTC, FraserGreenroyd commented
Merging per agreement with @IsakNaslundBh following updates to required checks from `check-installer` to `installer` (and needing to include versioning).

![image](https://user-images.githubusercontent.com/18049174/120506504-e4375980-c3bd-11eb-8037-f1df44ee1293.png)

2021-06-02 15:16 UTC, merged