Set up build configurations and references for GSA10.1 build
BHoM/GSA_Toolkit pull request #243
Opened 2021-06-02 16:30 UTC by IsakNaslundBh

### Issues addressed by this PR

Handles initial setup of #242 

 

- Adding gsa dll reference for GSA 10.1 to libs folder
- Setting up build configs for version 8.7 and 10.1
- Updating usings where needed
- setting up different adapter name dependant on build config

 ### Test files

 ### Changelog

 ### Additional comments

Should build as before for the previous Debug and Release builds, with GSAAdapter being the resulting class name. Will look into removing this and version GSAAdapter to the 8.7 build after 4.2 beta has been released.

@FraserGreenroyd adding you in for general compliance check. DO not expect you to test the code, just making sure I am not adding anything here that will be in the way for the release. The intention is that only the new builds should be different from before, while the default builds should remain unaffected

2021-06-03 16:17 UTC, annastigenberg submitted a review, later dismissed

2021-06-03 16:21 UTC, annastigenberg commented
Tested various old scripts using the GSA adapter, using push/ pull/ update etc, after compiling the 'debug' build. All work well.

2021-06-04 08:02 UTC, FraserGreenroyd requested changes
The suggested change can be ignored if you want.

My actual request for changes would be to include an `altConfigs.txt` file (see an example [here](https://github.com/BHoM/Revit_Toolkit/blob/master/altConfigs.txt)) that would allow BHoMBot to check both configurations in a `check core` check (this doesn't impact the installers).

Can I confirm the default build at the moment is still targeting 8_7 (does impact installers) (which is also the purpose of the first code comment).

Otherwise, from a CI perspective I'm happy with this.

2021-06-04 08:55 UTC, IsakNaslundBh commented on GSA_Adapter/AdapterActions/Execute.cs
> +#else
The default build is targeting GSA 8.7. WHat I did though is that I did _not_ define any constants for the default debug and release builds, so they should still revert to the `#else` case. This essentially means that we will have two identical builds. GSAAdapter and GSA8_7Adapter will be doing the exact same thing.

My reasoning for setting it up this way is that I did not want this PR to impact the beta release in any way at all. Plan (which I will document on the issue if we agree with this strategy) is that we remove the GSAAdapter in milestone 4.3, with proper versioning and everything, and only have the versioned builds left. Basically, remove default Debug and Release builds and remove the else statement.

Does that make sense?

2021-06-04 09:16 UTC, FraserGreenroyd commented on GSA_Adapter/AdapterActions/Execute.cs
> +#else
That does make sense.

If we don't change the configs for the installer (which is what we're recommending here, only adding one for `core`) then the 4.2 beta will be unchanged, so then doing a full upgrade in 4.3 with versioning is probably a good plan, I'd support that as a roll out.

2021-06-04 13:43 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-06-04 14:19 UTC, FraserGreenroyd approved these changes
Approved with discussion with @IsakNaslundBh

2021-06-04 14:19 UTC, merged