Add implementation of Exit command
BHoM/GSA_Toolkit pull request #249
Opened 2021-08-19 13:04 UTC by IsakNaslundBh

### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/303

 ### Issues addressed by this PR

 Closes #248

 

Adding support for the Exit command

 ### Test files

 ### Changelog

 ### Additional comments

2021-08-31 09:45 UTC, peterjamesnugent requested changes
Missing punctuation but otherwise code looks good - unable to test with GSA.

2021-08-31 09:45 UTC, peterjamesnugent commented on GSA_Adapter/AdapterActions/Execute.cs
> +                    Engine.Reflection.Compute.RecordError("Could not find the running GSA process");
```suggestion
                    Engine.Reflection.Compute.RecordError("Could not find the running GSA process.");
```

2021-08-31 10:40 UTC, peterjamesnugent approved these changes

2021-08-31 15:59 UTC, alelom submitted a review, later dismissed
LGTM. Tested and behaving as it should. 

Suggested a couple of small changes that I believe good practices, not essential.  
If accepted I will quickly re-approve.

2021-09-01 07:25 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-09-01 07:29 UTC, alelom submitted a review, later dismissed
Re-approving

2021-09-06 08:40 UTC, FraserGreenroyd approved these changes
@alelom previously approved this, @IsakNaslundBh has only added a `null-check` in his final commit. Owing to @alelom being on leave, I am approving this to unblock @IsakNaslundBh based on the final commit, and leaving merge decisions to @IsakNaslundBh on the basis that I have not actively tested this, only reviewed the final commit.

2021-09-06 08:51 UTC, IsakNaslundBh commented
@BHoMBot check core

2021-09-07 15:36 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2021-09-08 07:16 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2021-09-08 07:17 UTC, merged