Read load combination with parantheses
BHoM/GSA_Toolkit pull request #283
Opened 2023-03-10 16:52 UTC by johannaisak

Added if statement that replaces for example "1.5(L1 + L2)" with "1.5L1 + 1.5L2" when reading load combinations. There is probably a cleverer way of coding this?!

Please check that this works if you open the model in GSA 10.1 too.

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #282

 

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/GSA_Toolkit/%23283-Read-load-combinations-with-parantheses?csf=1&web=1&e=oeKcYD

 ### Changelog

 ### Additional comments

2023-03-11 20:00 UTC, FraserGreenroyd requested changes
Some nice string array handling going on there @johannaisak ! 😄

2023-03-17 11:48 UTC, TosteSkDa approved these changes
Tested for both GSA8.7 and 10.1. Displays desired load combinations correctly.

2023-04-14 13:28 UTC, johannaisak commented
@BHoMBot check compliance
@BHoMBot check required

2023-04-14 13:52 UTC, FraserGreenroyd approved these changes
All of my changes have been addressed, I have reviewed the code only and not any aspect of the functionality.

2023-04-14 14:03 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2023-04-14 14:22 UTC, merged