Fixed CAT section bar pull errors
BHoM/GSA_Toolkit pull request #293
Opened 2023-04-03 14:22 UTC by TosteSkDa

Fixed bug where bars with CAT CHS sections couldn't be pulled from GSA because it expected an array with more items. Separated IF clause for CHS and RHS fixed it. CHS only has diameter and thickness while RHS has height, width, thickness. Results in different arrays.

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #264 

 

 ### Test files

 ### Changelog

 ### Additional comments

2023-04-14 09:30 UTC, johannaisak requested changes
The code looks good and works as expected! However, in GSA10 it now fails further down in the code. This is because GSA10 uses space while GSA8.7 uses % in the strings. For example "CAT CHS CHS193x6.3 19990407" vs "CAT%CHS%CHS193x6.3%19990407". The code deals with this with the variable "splitChar" (defined higher up in the code) but that hadn't been updated in this bit of code. Please can you replace all the % in the RHS and CHS bits with splitChar instead?

2023-04-21 11:05 UTC, TosteSkDa commented
> The code looks good and works as expected! However, in GSA10 it now fails further down in the code. This is because GSA10 uses space while GSA8.7 uses % in the strings. For example "CAT CHS CHS193x6.3 19990407" vs "CAT%CHS%CHS193x6.3%19990407". The code deals with this with the variable "splitChar" (defined higher up in the code) but that hadn't been updated in this bit of code. Please can you replace all the % in the RHS and CHS bits with splitChar instead?

Fixed this now! :)

2023-04-21 15:19 UTC, johannaisak reviewed
Tested after updates and all works as expected, code looks good!

2023-04-21 15:19 UTC, johannaisak approved these changes
Tested after updates and all works as expected, code looks good!

2023-04-24 05:16 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2023-05-02 14:21 UTC, merged