Add fallback method for ToGsaString and CreateObject
BHoM/GSA_Toolkit pull request #317
Opened 2024-03-21 17:23 UTC by peterjamesnugent

### Issues addressed by this PR

 Closes #316 

 

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/Burohappold_BHoM_v7.1/Structures%20-%20Create%20read%20loads/BuroHappold_BHoM_v7.1.beta_Create%20read%20loads.gh?csf=1&web=1&e=c84a3u

 ### Changelog

- Added fallback methods for `ILoad` and all `BHoMObjects` were a useful error message is returned when the object is not supported (as opposed to a C# exception.

 ### Additional comments

I do not have GSA installed so would appreciate a quick test on this so I can make any changes as necessary.

2024-03-21 18:41 UTC, FraserGreenroyd requested changes
Minor comments

2024-03-21 18:41 UTC, FraserGreenroyd commented on GSA_Adapter/CRUD/Create.cs
> +            Compute.RecordError($"{obj.GetType()} is not implemented for GSA_Toolkit.");
```suggestion
            Compute.RecordError($"Pushing object of type {obj.GetType()} is not implemented for GSA_Toolkit.");
```

2024-03-21 18:41 UTC, FraserGreenroyd commented on GSA_Adapter/Convert/ToGsa/Loads/Load.cs
> +        public static List<string> ToGsaString(this ILoad load, double[] unitFactors)
This method can be private

2024-03-21 18:41 UTC, peterjamesnugent commented
@BHoMBot check documentation compliance
@BHoMBot check code-compliance

2024-03-21 18:42 UTC, peterjamesnugent commented
@BHoMBot check documentation-compliance

2024-03-21 19:03 UTC, FraserGreenroyd approved these changes
Looks good on code review, happy to merge for testing via beta artefacts if you wish @peterjamesnugent - your choice

2024-03-21 19:03 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2024-03-21 19:05 UTC, peterjamesnugent commented
@FraserGreenroyd I have a review lined up tomorrow so lets wait for that.

2024-03-22 08:28 UTC, IsakNaslundBh requested changes
See comments below. Most critical is to remove the backup method as that is already handled for the general case in the convert methods, and adding it makes it impossible to push most object types.

2024-03-22 08:28 UTC, IsakNaslundBh commented on GSA_Adapter/CRUD/Create.cs
> +
```suggestion

```

This method should not be added. Conflicts with main method on line 97 of this file as well as method on line 116 for section properties. Please remove.

This is already handled for the general case here:

https://github.com/BHoM/GSA_Toolkit/blob/94f9ece4c98b32834283658dbab59bb122b3dfb8/GSA_Adapter/Convert/ToGsa/_ToGsa.cs#L134-L139

2024-03-22 08:28 UTC, IsakNaslundBh commented on GSA_Adapter/Convert/ToGsa/Loads/Load.cs
> +            Engine.Base.Compute.RecordError($"Pushing load of type {load.GetType()} is not implemented for GSA_Toolkit.");
```suggestion
            NotSupportedWarning(load.GetType(), "Loads");
```

Can use the standardised warning message here.

2024-03-22 10:11 UTC, IsakNaslundBh requested changes
Some additional changes required. Have discussed in call with @peterjamesnugent

2024-03-22 11:07 UTC, IsakNaslundBh approved these changes
Happy with this now. Supported loads as well as other supported object types push as expected and unsupported load types now gives correct errors rather than hard to understand exceptions. Code changes looks good and tests fine. Approved!

2024-03-22 11:08 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2024-03-22 11:09 UTC, IsakNaslundBh commented
@BHoMBot check required

2024-03-22 11:41 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2024-03-22 11:42 UTC, merged